### ISSUE TITLE
Error with PropTypes when trying to run on Android

### ISSUE THREAD

**Issue by Enchufadoo** [aryaminus/RN-voice-video-call#1]
Hi, I get the following error trying to install the project:

![imagen](https://user-images.githubusercontent.com/1263356/32411677-7d0d6f90-c1c0-11e7-82f9-55b404a6e738.png)

Searching a little I think it's because of this

https://stackoverflow.com/a/44573437

That since version 15.5 PropTypes has it's own package

In the package.json I see this "react": "^16.0.0-alpha.12",
And in this is the line that causes the error

``` 
import React from 'react';

const {
  Component,
  PropTypes
} = React;
```
on index.android.js

I know nothing about react BTW!

**Comment by aryaminus** [comment]
PropTypes have been depreciated, either install it separately or for now don't import proptypes. I haven't used it in the build as a main component

**Comment by Enchufadoo** [comment]
what? you clearly use it in the code.

**Comment by aryaminus** [comment]
Well I had used in Keypad.js , but it does not have any depending variables currently. Either way just:
```
$ npm install --save prop-types
```
And import:
```
import PropTypes from 'prop-types';
```
Problem persists, then remove ^ from ^16.0.0-alpha.12 and upgrade the packages
