### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by baranpirincal** [aryaminus/RN-voice-video-call#3]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by aryaminus** [comment]
Sure, any kind of help would be appreciated

**Comment by baranpirincal** [comment]
@aryaminus 

Hey again :)

Do you have an any idea about design decisions?

I examined your README file and information video and I saw that there is a banana on starting page of application. Do you want me to use it on design? In my opinion it can be interesting :)

I am waiting your comments!

**Comment by aryaminus** [comment]
I leave the creative decision up-to you. The banana was just used to link all my other projects when someone follows the my YouTube tutorials
