### ISSUE TITLE
Error when call

### ISSUE THREAD

**Issue by vickychauhanbss** [aryaminus/RN-voice-video-call#4]
when i click on call button it says can't create dialog please help

**Comment by aryaminus** [comment]
Try to be more specific. Make sure you have added the respective voximplant credentials

**Comment by findelallc** [comment]
Where to add voximplant credentials?

**Comment by aryaminus** [comment]
@findela [Here](https://github.com/aryaminus/RN-voice-video-call/blob/master/app/components/Login.js#L65)

Closing due to insufficient information
